name: apps-platform
recipe: laravel
config:
  composer_version: '1.10.1'
  php: '7.1'
  webroot: public
  xdebug: true

services:
  pma:
    type: phpmyadmin
    hosts:
      - database
  node:
    type: node:10
    build:
      - npm install && npm run dev

proxy:
  pma:
    - pma.lndo.site

tooling:
  npm:
    service: node
  node:
    service: node
